CREATE TABLE Tasit(
    id INTEGER AUTO_INCREMENT NOT NULL ,
    tc VARCHAR(255) NOT NULL ,
    ad VARCHAR(255) NOT NULL ,
    adres VARCHAR(255) NOT NULL ,
    plaka VARCHAR(255) NOT NULL ,
    marka VARCHAR(255) NOT NULL ,
    model VARCHAR(255) NOT NULL ,
    PRIMARY KEY (id)
);

CREATE TABLE Araba(
    id INTEGER AUTO_INCREMENT NOT NULL ,
    marka VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);